conky.config = {
    lua_load = "~/.config/conky-catppuccin/lua/dashboard.lua",
    update_interval = 1,
    total_run_times = 0,
    background = false,
    cpu_avg_samples = 2,
    net_avg_samples = 2,
    use_xft = true,
    override_utf8_locale = true,
    font = "JetBrainsMono Nerd Font:size=11",
    double_buffer = true,
    own_window = true,
    own_window_type = "desktop",
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = "undecorated,below,sticky,skip_taskbar,skip_pager",
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    alignment = "top_left",
    minimum_width = 360,
    minimum_height = 720,
    gap_x = 55,
    gap_y = 45,
    default_color = "CDD6F4",
    no_buffers = true
}

conky.text = [[
${font JetBrains Mono:size=28}
${time %H:%M}

${font JetBrains Mono:size=14}
${time %A}

${font JetBrains Mono:size=11}
${time %d %B %Y}

${color A6E3A1}󰍛 CPU${alignr}${cpu}%
${color A6E3A1}${cpubar 2,260}

${color 94E2D5}󰘚 RAM${alignr}${memperc}%
${color 94E2D5}${membar 2,260}

${color F9E2AF}󰋊 SSD${alignr}${fs_used_perc /}%
${color F9E2AF}${fs_bar 2,260 /}

${color F38BA8} Temperatura${alignr}${execi 5 sensors | awk '/Package id 0:/ {print $4}'}

${color F5C2E7} Bateria${alignr}${battery_percent BAT0}%
${color F5C2E7}${battery_bar 2,260 BAT0}

${color 89DCEB} Wi-Fi
${wireless_essid wlp0s20f3}
]];
