conky.config = {
    own_window = true,
    own_window_type = 'desktop',

    own_window_argb_visual = true,
    own_window_argb_value = 0,

    double_buffer = true,

    use_xft = true,
    font = 'JetBrains Mono:size=18',

    alignment = 'top_left',
    gap_x = 50,
    gap_y = 50,

    update_interval = 1,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,

    default_color = 'FFFFFF',
};

conky.text = [[
Conky OK

${time %H:%M:%S}
]];
